# Generated by Django 4.1.2 on 2022-10-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citi',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='citi',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='citi',
            new_name='city',
        ),
    ]
