# Generated by Django 4.1.2 on 2022-10-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_citi_city_rename_citi_city_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='citi',
            new_name='city',
        ),
    ]
