# Generated by Django 4.1.2 on 2022-11-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_middleware'),
    ]

    operations = [
        migrations.AddField(
            model_name='middleware',
            name='json',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='middleware',
            name='method',
            field=models.CharField(choices=[('GE', 'GET'), ('PO', 'POST'), ('HE', 'HEAD'), ('DE', 'DELETE')], max_length=10),
        ),
    ]
