# Generated by Django 4.1.2 on 2022-11-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_middleware_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middleware',
            name='method',
            field=models.CharField(choices=[('GE', 'GET'), ('PO', 'POST')], max_length=2),
        ),
    ]
